name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: fluid-acrobat-440707-v4

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-gke-cluster --region us-central1
          
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s-manifests/patient-deployment.yaml
          kubectl apply -f k8s-manifests/patient-service.yaml
          kubectl apply -f k8s-manifests/appointment-deployment.yaml
          kubectl apply -f k8s-manifests/appointment-service.yaml
          kubectl apply -f k8s-manifests/ingress.yaml

